In [113]:
import numpy as np
import numpy.random as rand

In [114]:
a = np.array([2, 5, 10, 15, 50, 17, 8])
b = np.zeros((4, 5)) 
c = np.ones((4, 5))
d = np.arange(1, 13, 2) # создает последовательность, начиная с 1 до 13 с шагом 2
e = np.random.randint(0, 33, (5, 5)) # создает массив из случайных чисел от 0 до 33

In [115]:
print(b.shape, b.dtype) # атрибуты, котрые показывают форму массива, и тип значаний внутри массива

(4, 5) float64


In [116]:
print(c[1][1]) # выводит элемент 1 строки и 1 столбца матрицы c

1.0


In [117]:
print(a[2:5]) # выводит элементы массива с 3 по 5 включая

[10 15 50]


In [118]:
print(b + c) # сложение матриц

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [119]:
print(b*c) # умножение матриц

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [120]:
print(np.mean(d, axis = None)) # Выводит среднее значение по всему массиву

6.0
